input_variables: [context, input_question]
output_parser: null
messages:
  - role: user
    prompt:
      template: 'Ты являешься помощником при выполнении заданий, связанных 
      с ответами на вопросы. Используй следующие фрагменты найденного контекста, 
      чтобы ответить на вопрос. Если ты не знаешь ответа, просто скажи, 
      что не знаешь. Используй не более трех предложений и будь лаконичным в ответе.
      Вопрос: {input_question} 
      Контекст: {context} 
      Ответ:'
template_format: f-string
_type: chat